import type { JobHuntingTypeContent, JobHuntingTypeKey } from "./types";

export const JOB_HUNTING_TYPE_CONTENT: Record<JobHuntingTypeKey, JobHuntingTypeContent> = {
  logical: {
    key: "logical",
    name: "分析型",
    summary:
      "物事を要素に分解し、根拠を持って筋道立てて考えるタイプです。感覚より事実・データを重視します。",
    strengths: ["情報整理力", "論理的な説明力", "課題の原因を特定する力"],
    weaknesses: ["考えすぎて動き出しが遅くなることがある", "感情面のフォローが後回しになりがち"],
    suitableJobs: ["企画・戦略職", "データ分析職", "コンサルティング", "研究開発"],
    suitableCulture: ["意思決定の根拠を大事にする文化", "議論がオープンな環境"],
    avoidEnvironments: ["勢いや気合いだけで意思決定が進む環境", "根拠を問うと否定的に扱われる環境"],
    selfPrDirection: "「なぜそう考えたか」の筋道を示しながら、課題解決に向けて筋道立てて動けることを伝える方向性。",
  },
  empathetic: {
    key: "empathetic",
    name: "共感型",
    summary: "相手の気持ちや状況を汲み取りながら関わるタイプです。人との関係性の中で力を発揮します。",
    strengths: ["傾聴力", "相手の状況に合わせた対応力", "信頼関係を築く力"],
    weaknesses: ["相手に合わせすぎて自分の意見を出しにくいことがある", "対立を避けがち"],
    suitableJobs: ["人事", "カスタマーサクセス", "営業", "対人支援・教育系"],
    suitableCulture: ["対話を重視するチーム", "相手の状況に配慮する文化"],
    avoidEnvironments: ["数字や成果だけで人を評価する環境", "個人プレー中心で対話が少ない環境"],
    selfPrDirection: "人との関わりの中でどう相手の状況を汲み取り、関係性を築いてきたかを伝える方向性。",
  },
  challenger: {
    key: "challenger",
    name: "挑戦型",
    summary: "新しいことや変化に前向きに飛び込み、行動しながら学んでいくタイプです。",
    strengths: ["行動力", "変化への適応力", "未経験の領域に踏み出す度胸"],
    weaknesses: ["準備より先に動いてしまうことがある", "同じことの繰り返しに飽きやすい"],
    suitableJobs: ["新規事業", "スタートアップ", "営業(新規開拓)", "海外事業"],
    suitableCulture: ["変化のスピードが速い環境", "挑戦を後押しする文化"],
    avoidEnvironments: ["前例踏襲が絶対とされる環境", "小さな変化にも時間がかかる環境"],
    selfPrDirection: "未経験の状況に自ら踏み出し、行動しながら学び取ってきた経験を伝える方向性。",
  },
  stability: {
    key: "stability",
    name: "安定型",
    summary: "計画的にコツコツ積み上げ、着実に成果を出していくタイプです。",
    strengths: ["継続力", "計画性", "地道な積み重ねを苦にしない粘り強さ"],
    weaknesses: ["急な方針転換への対応に時間がかかることがある", "リスクを取ることに慎重になりすぎる場合がある"],
    suitableJobs: ["管理部門", "品質管理", "経理・財務", "オペレーション"],
    suitableCulture: ["計画性が評価される環境", "積み重ねを正しく評価してくれる文化"],
    avoidEnvironments: ["方針が頻繁に変わる環境", "場当たり的な進め方が常態化している環境"],
    selfPrDirection: "地道な取り組みをどう継続し、着実に成果につなげてきたかを伝える方向性。",
  },
  independent: {
    key: "independent",
    name: "独立型",
    summary: "自分のペースと裁量を大事にしながら、自律的に物事を進めていくタイプです。",
    strengths: ["自走力", "自己管理力", "自分なりのやり方を追求する力"],
    weaknesses: ["周囲への共有・報告が後回しになりがち", "指示が細かい環境ではやりづらさを感じやすい"],
    suitableJobs: ["専門職", "エンジニア", "クリエイティブ職", "個人裁量の大きい営業"],
    suitableCulture: ["裁量権が大きい環境", "成果で評価される文化"],
    avoidEnvironments: ["細かい管理・報告が常に求められる環境", "個人の裁量がほとんどない環境"],
    selfPrDirection: "自分で考え、裁量を持って物事を最後までやり切ってきた経験を伝える方向性。",
  },
  harmonizer: {
    key: "harmonizer",
    name: "調整型",
    summary: "チーム全体のバランスを見ながら、意見の違いをまとめていくタイプです。",
    strengths: ["調整力", "全体を俯瞰する力", "意見が対立したときの仲介力"],
    weaknesses: ["自分の意見を後回しにしがち", "決断が必要な場面で時間がかかることがある"],
    suitableJobs: ["プロジェクトマネジメント", "総務・人事", "秘書・アシスタント職", "イベント運営"],
    suitableCulture: ["チームワークを重視する環境", "役割分担が明確な文化"],
    avoidEnvironments: ["個人の成果だけが評価される環境", "対立を力任せに解決しようとする文化"],
    selfPrDirection: "チームの中で意見の違いをどう調整し、全体をまとめてきたかを伝える方向性。",
  },
};
